apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cesium
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://github.com/fxttr/cesium.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cesium
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/overlays/dev/
  prune: true
  sourceRef:
    kind: GitRepository
    name: cesium
  targetNamespace: cesium
  decryption:
    provider: sops
    secretRef:
      name: sops-age